# Generated by Django 2.2.7 on 2019-12-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='testdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.RenameField(
            model_name='product_cart',
            old_name='cart_productid',
            new_name='cart_product',
        ),
        migrations.RenameField(
            model_name='product_cart',
            old_name='cart_usr_id',
            new_name='cart_usr',
        ),
        migrations.RenameField(
            model_name='product_quantity',
            old_name='pro_id',
            new_name='pro',
        ),
    ]
